### ISSUE TITLE
M09-Lab 16 - Monitoring Application Performance: Lacks appsettings to deploy correctly

### ISSUE THREAD

**Issue by rob-foulkrod** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#560]
### What happened?

Exercise : 1
Task: 2
Step: 10 - 12

Description of issue: the Azure App Service deploy step requires configuration to deploy correctly

Repro steps:
Current deployment, without the correct App Settings will result in a 500 error

Step 12 should look like

```
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'MTTManaged'
        appType: 'webApp'
        WebAppName: 'az400eshoponweb177112039'
        packageForLinux: '$(Build.ArtifactStagingDirectory)/**/Web.zip'
        AppSettings: '-UseOnlyInMemoryDatabase true -ASPNETCORE_ENVIRONMENT Development'
```

### Lab

Other

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)
