### ISSUE TITLE
Integrating Azure Key Vault with Azure DevOps : Docker-compose task problem

### ISSUE THREAD

**Issue by chtourou-youssef** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#567]
### What happened?

Exercise : 1
Task: 2
Step: 3

Description of issue:

The pipeline dosen't work with the new `docker compose` version ( without - between docker and compose )

The error message is :  ### Docker Compose was not found. You can provide the path to docker-compose via 'dockerComposePath'

Repro steps:
add dockerComposePath to DockerCompose@0 task
dockerComposePath: '/home/vsts/.docker/cli-plugins/docker-compose' so the task will be like that : 

```
    - task: DockerCompose@0
      displayName: Build Docker Compose
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: '$(azureserviceconnection)'
        azureContainerRegistry: '$(acrloginserver)'
        dockerComposeFile: '**/docker-compose.yml'
        projectName: 
        action: 'Build services'
        additionalImageTags: '$(Build.BuildNumber)'
        includeLatestTag: true
        dockerComposePath: '/usr/libexec/docker/cli-plugins/docker-compose'
    - task: DockerCompose@0
      displayName: Push Docker Compose
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: $(azureserviceconnection)
        azureContainerRegistry: '$(acrloginserver)'
        dockerComposeFile: '**/docker-compose.yml'
        projectName: 
        action: 'Push services'
        additionalImageTags: '$(Build.BuildNumber)'
        includeLatestTag: true
        dockerComposePath: '/usr/libexec/docker/cli-plugins/docker-compose'
```

### Lab

Integrate Azure Key Vault with Azure DevOps

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)
